version: "2"

services:
  nexus:
      image: vulcanos/nexus3-tls
      volumes:
        - "nexus-data:/nexus-data"
      ports:
        - "8443:8443"
        - "5443:5443"
      env_file:
        - .env

volumes:
  nexus-data: {}

networks:
  nexus:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24