version: "2"

services:
  nexus:
      build:
        context: build/
      volumes:
        - "nexus-data:/nexus-data"
      ports:
        - "8081:8081"

volumes:
  nexus-data: {}

networks:
  nexus:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24