apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: nexus3

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: nexus-pvc
      namespace: nexus3
    spec:
      storageClassName: nexus-sc
      accessModes:
        - ReadWriteMany
      volumeMode: Filesystem
      resources:
        requests:
          storage: 20Gi

  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: nexus-sc
      namespace: nexus3
    volumeBindingMode: Immediate
    provisioner: local

  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: nexus-data
      namespace: nexus3
    spec:
      storageClassName: nexus-sc
      capacity:
        storage: 20Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteMany
      hostPath:
        path: "/data/pv001"

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nexus
      namespace: nexus3
      labels:
        istio-injection: enabled
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: nexus
      template:
        metadata:
          labels:
            istio-injection: enabled
            app: nexus
        spec:
          containers:
            # - image: sonatype/nexus3:latest
            - image: vulcanos/nexus3-tls:latest
              name: nexus
              resources:
                requests:
                  cpu: "500m"
                  memory: "2Gi"
                limits:
                  memory: "4Gi"
                  cpu: "4000m"
              envFrom:
                - configMapRef:
                    name: nexus-cert-config
              ports:
                - containerPort: 8443
                - containerPort: 5443
              volumeMounts:
                - mountPath: /nexus-data
                  name: nexus-data-volume
          volumes:
            - name: nexus-data-volume
              persistentVolumeClaim:
                claimName: nexus-pvc



  - apiVersion: v1
    kind: Service
    metadata:
      name: nexus-service
      namespace: nexus3
      labels:
        istio-injection: enabled
        app: nexus
        service: nexus
    spec:
      type: LoadBalancer
      ports:
        - port: 8443
          targetPort: 8443
          protocol: TCP
          name: https
        - port: 5443
          targetPort: 5443
          protocol: TCP
          name: https-docker-repo
      selector:
        app: nexus